# Generated by Django 5.2.6 on 2025-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='This is a test summary', verbose_name='خلاصه'),
            preserve_default=False,
        ),
    ]
