# Generated by Django 5.2.6 on 2025-10-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/default.jpeg', upload_to='covers'),
        ),
    ]
