# Generated by Django 5.2.6 on 2025-10-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='زندگی\u200cنامه'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='تاریخ تولد'),
        ),
    ]
